#!/usr/bin/env python
# -*- coding: UTF-8 -*-

# This file is part of Raise.
# Raise is a small build automation tool that ships with your software.
# Raise uses a MIT style license, and is hosted at https://github.com/workhorsy/raise .
# Copyright (c) 2012-2017 Matthew Brennan Jones <matthew.brennan.jones@gmail.com>
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

# Make sure we are in at least python 2.6
import sys
if sys.version_info < (2, 6):
	print("Python 2.6 or greater is required. Exiting ...")
	exit(1)

# Load the default imports
import os
import stat
import threading
if sys.version_info < (3, 0):
	from urllib2 import urlopen
else:
	from urllib.request import urlopen

# Get the location of Lib Raise for this version
LIB_RAISE_VERSION = '0.5.0 Dev'
RAISE_VERSION = 'master'
RAISE_BASE = 'https://raw.githubusercontent.com/workhorsy/raise/{0}/lib_raise/'.format(RAISE_VERSION)
RAISE_URLS = {
	'cpuinfo.py'                : '{0}cpuinfo.py'.format(RAISE_BASE),
	'findlib.py'                : '{0}findlib.py'.format(RAISE_BASE),
	'findlib_server.py'         : '{0}findlib_server.py'.format(RAISE_BASE),
	'osinfo.py'                 : '{0}osinfo.py'.format(RAISE_BASE),
	'raise'                     : '{0}lib_raise.py'.format(RAISE_BASE),
	'raise_ar'                  : '{0}lib_raise_ar.py'.format(RAISE_BASE),
	'raise_c'                   : '{0}lib_raise_c.py'.format(RAISE_BASE),
	'raise_config'              : '{0}lib_raise_config.py'.format(RAISE_BASE),
	'raise_cpu'                 : '{0}lib_raise_cpu.py'.format(RAISE_BASE),
	'raise_csharp'              : '{0}lib_raise_csharp.py'.format(RAISE_BASE),
	'raise_cxx'                 : '{0}lib_raise_cxx.py'.format(RAISE_BASE),
	'raise_d'                   : '{0}lib_raise_d.py'.format(RAISE_BASE),
	'raise_find'                : '{0}lib_raise_find.py'.format(RAISE_BASE),
	'raise_fs'                  : '{0}lib_raise_fs.py'.format(RAISE_BASE),
	'raise_helpers'             : '{0}lib_raise_helpers.py'.format(RAISE_BASE),
	'raise_java'                : '{0}lib_raise_java.py'.format(RAISE_BASE),
	'raise_linker'              : '{0}lib_raise_linker.py'.format(RAISE_BASE),
	'raise_process'             : '{0}lib_raise_process.py'.format(RAISE_BASE),
	'raise_python'              : '{0}lib_raise_python.py'.format(RAISE_BASE),
	'raise_terminal'            : '{0}lib_raise_terminal.py'.format(RAISE_BASE),
	'raise_users'               : '{0}lib_raise_users.py'.format(RAISE_BASE),
}

def friendly_size(data_length):
	retval = ''
	size_map = [
		{'B'  : 1},
		{'KB' : 1024.0},
		{'MB' : 1024000.0},
		{'GB' : 1024000000.0}
	]
	for i in size_map:
		for name, size in i.items():
			if data_length >= size:
				retval = '{0} {1}'.format(round(data_length / size, 2), name)
				break

	return retval

def update(dir_name):
	print("Downloading Lib Raise version {0} ...".format(LIB_RAISE_VERSION))

	if not os.path.isdir(dir_name):
		os.mkdir(dir_name)

	ts = []
	for module, url in RAISE_URLS.items():
		# Get the real name if a raise module
		if not module.endswith('.py'):
			module = "lib_{0}.py".format(module)

		t = Downloader(module, url, dir_name)
		t.daemon = True
		t.start()
		ts.append(t)

	for t in ts:
		t.join()
		if t.message:
			print(t.message)
		if not t.is_success:
			exit(1)

	print("Done!")


class Downloader(threading.Thread):
	def __init__(self, module, url, dir_name):
		super(Downloader, self).__init__()

		self.module = module
		self.url = url
		self.dir_name = dir_name
		self.is_success = False
		self.message = None

	def run(self):
		# Get the file name for script
		file_name = os.path.join(self.dir_name, self.module)

		# Download the file and call the cb after each chunk
		self._download_file(self.url, file_name)

		# Make the file executable
		os.chmod(file_name, 0o775 | stat.S_IXOTH)

	def _download_file(self, url, file_name):
		CHUNK_SIZE = 1024

		try:
			# Connect with HTTP
			response = urlopen(url)
			if response.code != 200:
				self.is_success = False
				self.message = 'Download failed. Exiting ...'
				exit(1)

			# Read the HTTP header
			content_length = int(response.headers['Content-Length'])
			data = b''
			data_length = 0

			# Read the HTTP body
			while True:
				chunk = response.read(CHUNK_SIZE)
				if not chunk:
					break

				data += chunk
				data_length += len(chunk)
				percent = round((float(data_length) / content_length)*100, 2)

				self._cb_dl_progress(file_name, chunk, data_length, CHUNK_SIZE, content_length, percent)
		except Exception as e:
			self.is_success = False
			self.message = 'Download failed. Exiting ...\n{0}\n{1}'.format(str(e), self.url)
			exit(1)

		# Write the file to disk
		self._cb_dl_done(file_name, data)

	def _cb_dl_progress(self, file_name, chunk, data_length, chunk_size, content_length, percent):
		pass

	def _cb_dl_done(self, file_name, data):
		# Make sure the downloaded file is python
		if not data.decode().startswith("#!/usr/bin/env python"):
			self.is_success = False
			self.message = 'The downloaded update was invalid. Make sure http://github.com can be accessed. Exiting ...'
			exit(1)

		# Save the file
		with open(file_name, 'wb') as f:
			f.write(data)

		self.is_success = True
		self.message = '    {0}'.format(file_name)

if __name__ == '__main__':
	needs_update = True
	dir_name = '.lib_raise/'

	# Get the arguments
	args = str(str.join(' ', sys.argv[1:]))

	# Get the location of the module files
	dirs = ['lib_raise/', '.lib_raise/', '../lib_raise/', '../../lib_raise/']
	for entry in dirs:
		if os.path.exists(entry):
			dir_name = entry
			has_files = True

			for module, url in RAISE_URLS.items():
				# Get the real name if a raise module
				if not module.endswith('.py'):
					module = 'lib_{0}.py'.format(module)
				module = os.path.join(entry, module)
				if not os.path.exists(module):
					has_files = False
			if has_files:
				needs_update = False

	# Print the version if that is the target
	if args == 'version':
		print(LIB_RAISE_VERSION)
		exit(0)
	# Print the version if that is the target
	elif args == 'help':
		print("COMMANDS:")
		print("    ./raise help    - Print the help menu")
		print("    ./raise version - Print the version of Raise")
		print("    ./raise update  - Downloads the Raise libraries into a directory named \".lib_raise\" or \"lib_raise\".")
		print("")
		print("OPTIONS:")
		print("    -plain    - Don't clear, don't use color, and fix the width to 79")
		print("    -nolineno - Don't print line numbers on error exit")
		print("    -inspect  - Print the source code to the target")
		print("    -arg=     - Pass an argument to the rscript")
		print("")
		exit(0)

	# Run update if that is the target
	if args == 'update':
		update(dir_name)
		exit(0)
	elif needs_update:
		update(dir_name)

	# Have the lib_raise.py file handle everything else
	actual = "{0}lib_raise.py".format(dir_name)
	rc = os.system('{0} {1} {2}'.format(sys.executable, actual, args))
	if hasattr(os, 'WIFEXITED') and os.WIFEXITED(rc):
		rc = os.WEXITSTATUS(rc)
	exit(rc)
